version: "3.7"

services:
  page_backend:
    build: .
    container_name: hypertech99s_page_backend
    restart: always
    ports:
     - "80:8000"
    volumes:
     - ./backend:/app
    depends_on:
     - page_database
  page_database:
    image: mysql:8.0.26
    container_name: hypertech99s_page_database
    restart: always
    ports:
      - "81:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=21-9424813
      - TZ=Asia/Seoul
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /home/admin/databases/page_database:/var/lib/mysql

